### ISSUE TITLE
errore di modulo non trovato dando ng serve 

### ISSUE THREAD

**Issue by francescolillo24** [luca-lezzerini/rubrica-mac#1]
lanciando ng serve --o si ottiene l errore mostrato nella scermata seguente:
![errore ](https://user-images.githubusercontent.com/78487863/107224352-9dd97b80-6a17-11eb-8619-e5b02f485b0f.PNG)

**Comment by francescolillo24** [comment]
b29016969e9c5a08103a0d5eb3167e70b25ec204

**Comment by luca-lezzerini** [comment]
Provi npm install @angular/cli nella cartella di progetto (dove esegue ng serve)

**Comment by luca-lezzerini** [comment]
Bisogna sempre dare npm install @angular/cli quando si clona il client!

**Comment by luca-lezzerini** [comment]
Per me è risolto. Verifichi e chiuda il ticket
