### ISSUE TITLE
Incomprensioni sulla traccia

### ISSUE THREAD

**Issue by marcobonaccorso** [luca-lezzerini/rubrica-mac#2]
punto "Recupera tutti i contatti: ritorna una lista di tutti i contatti in rubrica."
Cosa si intende? Il metodo vuole una visualizzazione completa della tabella dei contatti solo quando viene premuto il tasto recupera? E non quando vengono inseriti?

**Comment by luca-lezzerini** [comment]
Significa che bisogna prevedere un servizio che ritorni tutti i dati, ad esempio quando si accede all'inizio, altrimeni mostra una rubrica vuota finché non si fa qualcosa

**Comment by luca-lezzerini** [comment]
Mi chiude il ticket se la questione è risolta, per favore?

**Comment by marcobonaccorso** [comment]
> punto "Recupera tutti i contatti: ritorna una lista di tutti i contatti in rubrica."
> Cosa si intende? Il metodo vuole una visualizzazione completa della tabella dei contatti solo quando viene premuto il tasto recupera? E non quando vengono inseriti?
