### ISSUE TITLE
Errore ng serve --o

### ISSUE THREAD

**Issue by Alessandro-Urbani** [luca-lezzerini/rubrica-mac#3]
Quando faccio "ng serve --o" nella cartella client il prompt mi da l'errore riportato nello screenshot seguente, ho gia provato a rimuovere e reinstallare angular cli ma l'errore persiste
![Errore](https://user-images.githubusercontent.com/78544893/107568433-41c55180-6be7-11eb-9c40-13d889a0fcd3.PNG)

**Comment by luca-lezzerini** [comment]
Riprovi con npm i @angular/cli

**Comment by luca-lezzerini** [comment]
Provi a cancellare prima la cartella node_modules

**Comment by luca-lezzerini** [comment]
Mi chiude il ticket se la questione è risolta, per favore?
