### ISSUE TITLE
Errore su commit

### ISSUE THREAD

**Issue by ValeriaCom** [luca-lezzerini/rubrica-mac#4]
Dopo aver completato la parte lato server e aver committato ai miei colleghi, questi ultimi non riescono a vedere il commit.

**Comment by luca-lezzerini** [comment]
Ha fatto push? Se riceve un errore me lo giri.

**Comment by ValeriaCom** [comment]
Facendo push non succede nulla e i miei colleghi non riescono ancora a vedere il codice committato.  Ci riproveremo domani oppure attendiamo lunedì per avere un aiuto da Lei.

**Comment by luca-lezzerini** [comment]
Non mi risulta nessun commit sul server, l'ultimo è di Bonaccorso di tre giorni fa [Vedere qui](https://github.com/luca-lezzerini/rubrica-mac/commits/master)

È sicura di essere sul repository corretto rubrica-mac? Mi mette uno screenshot del GitHub Desktop, sia su scommit sia su history?

**Comment by luca-lezzerini** [comment]
Stasera o domattina mi posso connettere su meet. Mi mand un messaggio quando pensa di poterlo fare anche lei. Il mio cellulare è 346 665 3009

**Comment by ValeriaCom** [comment]
No, non siamo su rubrica-mac. Abbiamo creato un progetto ex novo ma non sappiamo come fare per farle vedere i vari commit. 

Cordialmente,
Comitogianni Valeria
