### ISSUE TITLE
errore su Run

### ISSUE THREAD

**Issue by ValeriaCom** [luca-lezzerini/rubrica-mac#5]
![CatturaErroreRun](https://user-images.githubusercontent.com/78487304/107849987-46645280-6dff-11eb-83eb-c1e5aa316be7.PNG)

**Comment by luca-lezzerini** [comment]
Mi può dare tutto il log? Basta selezionarlo tutto,vcopiarlo e incollarlo

**Comment by luca-lezzerini** [comment]
Provi a reimpostare la classe main, andando sulla radice del progetto, tasto destro, properties, run, main class e scelga con browse la classe main da utilizzare (ce n'è una sola). Forse così parte, altriemnti mi mandi tutto il log come scritto sopra

**Comment by ValeriaCom** [comment]
Risolto! Grazie!
